name: Conventional Commits

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  conventional-commits-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webiny/action-conventional-commits@v1.1.0
