name: Danger

on: [pull_request]

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Danger
        uses: danger/danger-js@11.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
