name: Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: |
          npm init -y
          npm install eslint --save-dev
          
      - name: Lint with ESLint
        run: |
          npx eslint . --ext .js
